services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - kimai
    restart: 'unless-stopped'
    volumes:
      - db:/var/lib/mysql
  kimai:
    image: kimai/kimai2:apache
    environment:
      - "DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}"
    restart: 'unless-stopped'
    ports:
      - ${WEB_PORT}:8001
    depends_on:
      - mysql
    networks:
      - kimai

networks:
  kimai:

volumes:
  db:
